instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user.forms import LoginForm
from django.contrib.auth import views as auth_views
from user import views as user_views
from post import views as post_views
from message import views as message_views
from notification import views as notification_views


urlpatterns = [
    path('', post_views.PostListView, name='post_list'),
    path('create/details/', post_views.PostCreateView.as_view(), name='post_create'),
    path('p/<int:pk>', post_views.SinglePostView, name='single_post_view'),
    path('comment/<int:pk>', post_views.CommentCreateView, name='post_comment_create'),
    path('reply/<int:pk>', post_views.ReplyCreateView, name='comment_reply_create'),
    path('search/', post_views.SearchView, name='search'),
    path('explore/', post_views.ExploreView.as_view(), name='explore'),
    path('admin/', admin.site.urls),

    path('like/<int:pk>/',post_views.LikeView.as_view(), name='post_like'),
    path('unlike/<int:pk>/',post_views.UnlikeView.as_view(), name='post_unlike'),
    path('share/search/',post_views.ShareProfileView, name='share_profile_search'),
    path('share/',post_views.ShareView.as_view(), name='post_share'),

    path('save/<int:pk>/',post_views.SaveView.as_view(), name='post_save'),
    path('unsave/<int:pk>/',post_views.UnsaveView.as_view(), name='post_unsave'),

    path('direct/inbox/', message_views.InboxListView, name='inbox_list'),
    path('direct/t/<int:pk>/', message_views.InboxDetailView, name='inbox_detail'),
    path('direct/profile/', message_views.InboxFindProfileView, name='inbox_find_profile'),
    path('direct/new/<int:pk>', message_views.InboxCreateView, name='inbox_create'),
    path('message/<int:pk>/', message_views.MessageCreateView, name='message_create'),
    path('direct/t/message/update/<int:pk>', message_views.MessageUpdateView, name='message_update'),


    path('notification/message/<int:pk>', notification_views.InboxNotificationView.as_view(), name='inbox_notification'),
    path('notification/<int:pk>', notification_views.NotificationView.as_view(), name='notification'),
    path('notification/display/<int:pk>', notification_views.NotificationDisplayView.as_view(), name='notification_display'),


    path('follow/', user_views.followView.as_view(), name='follow'),
    path('<str:username>/', user_views.profileView, name='profile'),
    path('<str:username>/saved/', user_views.savedDisplayView, name='saved'),
    path('accounts/emailsignup/', user_views.signupView, name='signup'),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('accounts/edit/', user_views.editView, name='edit'),
    path('accounts/password/change', user_views.change_password, name='change_password'),
    path('accounts/login/', user_views.LoginView.as_view(template_name="user/login.html",authentication_form=LoginForm), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password/reset', auth_views.PasswordResetView.as_view(template_name="user/password_reset.html"), name='password_reset'),
    path('accounts/password/reset/done', auth_views.PasswordResetDoneView.as_view(template_name="user/password_reset_done.html"), name='password_reset_done'),
    path('accounts/password/reset/confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html"), name='password_reset_confirm'),
    path('accounts/password/reset/complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name="user/password_reset_complete.html"), name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django.contrib.auth.models import User
import PIL.Image as Image


class Post(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner_posts')    
    photo = models.ImageField(upload_to="posts", default='default.jpg')
    caption = models.CharField(max_length=250,default='')

    created_at = models.DateTimeField(auto_now_add=True)
    
    comments = models.ManyToManyField(User, through='Comment', related_name='comment_post')
    likes = models.ManyToManyField(User, through='Like', related_name='like_post')
    saves = models.ManyToManyField(User, through='Save', related_name='save_post')

    
    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.photo.path)
        width, height = img.size  

        if height < width:
            left = (width - height) / 2
            right = (width + height) / 2
            top = 0
            bottom = height
            img = img.crop((left, top, right, bottom))

        elif width < height:
            left = 0
            right = width
            top = 0
            bottom = width
            img = img.crop((left, top, right, bottom))

        img.save(self.photo.path)


    def __str__(self):
        return f'{self.owner.username}: {self.caption[:15]}...'


class Like(models.Model) :
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_likes')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('owner', 'post')

    def __str__(self) :
        return '%s likes %s... post'%(self.owner.username, self.post.caption[:15])


class Save(models.Model) :
    owner = models.ForeignKey(User, related_name='save_owner', on_delete=models.CASCADE)    
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_saves')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('owner', 'post')

    def __str__(self) :
        return '%s saved %s... post'%(self.owner.username, self.post.caption[:15])


class Comment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)    
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments')
    text = models.CharField(max_length=250, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return f'{self.owner.username}\'s comment on "{self.post.caption[:15]}..." post: {self.text}'

class Reply(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)    
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comment_replies')
    text = models.CharField(max_length=250, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return f'{self.owner.username}\'s reply to "{self.comment.text[:15]}..." comment: {self.text[:15]}...'
    

post/forms.py
# forms.py 
from django import forms 
from .models import *

class CommentForm(forms.Form):
    text = forms.CharField(required=False, max_length=250, min_length=1, strip=True, widget= forms.TextInput(attrs={'placeholder':'Add a comment...'}))


class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('photo', 'caption') 
        widgets = {
            'photo': forms.FileInput(attrs={'id':'file-upload'}),
            'caption': forms.TextInput(attrs={'placeholder': 'Add a caption...', 'class':'post-create-form'}),
        }
    
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['caption'].label = ""

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from .models import Profile
from django.contrib.auth.forms import PasswordChangeForm


#using first_name as full_name 
class SignUpForm(UserCreationForm):
    username   = forms.CharField(widget=(forms.TextInput(attrs={'class': 'signup-form', 'placeholder': 'Username'})),label='')
    first_name = forms.CharField(widget=(forms.TextInput(attrs={'class': 'signup-form', 'placeholder': 'Full Name'})),label='', max_length=32)
    email      = forms.EmailField(widget=(forms.EmailInput(attrs={'class': 'signup-form', 'placeholder': 'Email'})),label='', max_length=64)
    password1  = forms.CharField(widget=(forms.PasswordInput(attrs={'class': 'signup-form', 'placeholder': 'Password'})),label='')
    password2  = forms.CharField(widget=(forms.PasswordInput(attrs={'class': 'signup-form', 'placeholder': 'Password Again'})),label='')

    def clean(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(f"Another account is using {email}")
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username isn't available. Please try another.")

        return self.cleaned_data

    class Meta:
        model = User
        fields = ('email', 'first_name','username', 'password1','password2')


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=(forms.TextInput(attrs={'class': 'signup-form', 'placeholder': 'Username'})),label='')
    password = forms.CharField(widget=(forms.PasswordInput(attrs={'class': 'signup-form', 'placeholder': 'Password'})),label='')


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'username', 'email']

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget = forms.TextInput(attrs={'class': 'user-edit-form','placeholder': 'Name'},)
        self.fields['first_name'].label = 'Name'
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'user-edit-form','placeholder': 'Username'},)
        self.fields['username'].help_text = None
        self.fields['email'].widget = forms.TextInput(attrs={'class': 'user-edit-form','placeholder': 'Email'},)
        self.fields['email'].label = 'Email'


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo','website','bio', 'phone']

    def __init__(self, *args, **kwargs):
        super(ProfileEditForm, self).__init__(*args, **kwargs)

        self.fields['website'].widget = forms.TextInput(attrs={'class': 'user-edit-form','placeholder': 'Website'},)
        self.fields['bio'].widget = forms.TextInput(attrs={'class': 'user-edit-form','placeholder': 'Bio'},)
        self.fields['phone'].widget = forms.TextInput(attrs={'class': 'user-edit-form','placeholder': 'Phone'},)

class passwordChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(passwordChangeForm, self).__init__(*args, **kwargs)

        self.fields['old_password'].widget = forms.PasswordInput(attrs={'class': 'user-edit-form','placeholder': 'current passowrd'},)
        self.fields['new_password1'].widget = forms.PasswordInput(attrs={'class': 'user-edit-form','placeholder': 'new passowrd'},)
        self.fields['new_password2'].widget = forms.PasswordInput(attrs={'class': 'user-edit-form','placeholder': 'confirm passowrd'},)

post/templates/post/like_count.html
{% if post.post_likes.count > 1 %}
<p>{{post.post_likes.count}} likes</p>
{% elif post.post_likes.count == 1 %}
<p>{{post.post_likes.count}} like</p>
{% else %}
<p></p>
{% endif %}

post/templates/post/post_create.html
{% extends "user/base.html" %}
{% load static %}

{% block title %} Create Post {% endblock %}
{% block content %}

<style>

body{
          margin: 0;
          padding: 0;
          background: black;
      }
    </style>      
  <div class='card col-12 col-sm-8 col-md-5 p-4 text-center p-4 pt-5' style="margin-top:5rem">
      <p><img src="{% static 'img/pro-i.jpg' %}" alt="logo" style="width:180px"></p>  
      <h5>Create New Post</h5>
      <p class='text-muted mb-5'>Upload an image and add a caption.</p>

      <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="input-group d-flex justify-content-center mb-3">
            <div class="custom-file col-11">
              {{ form.photo }}
              <label class="custom-file-label d-inline" for="file-upload" style="background-color: #fafafa;">Your view</label>
            </div>
          </div>
          {{ form.caption }}
          <input type="submit" class="btn btn-primary col-6 mt-2 p-1" value="Upload" style="font-size: 0.9rem; font-weight: 600; background-color:#0095f6;" />
          <input type="hidden" name="next" value="{{ next }}" />
      </form>
  </div>

  <footer class='col-12 mb-2 mt-5 justify-content-center' style="font-size: 0.75rem; color:#8e8e8e">
      <p class='text-center'style='cursor:pointer;'> About  &emsp;Blog  &emsp;Jobs &emsp; Help &emsp; API  &emsp;Privacy &emsp; Terms &emsp; Top Accounts &emsp; Hashtags &emsp;Locations</p>
      <p class='text-center'style='cursor:pointer;'> English  © 2021 Pro-instrumentals</p>
  </footer>

  <style>
      .card{
          background-color: black!important;
          border:1px solid black !important;
      }
      label{
          display: none !important;
      }
      #id_email{
          border-radius: 5px;
          border: 1px solid #e5e5e5 !important;
          width:85% !important;
          height:2rem !important;
          outline:none;
          padding:10px;
          background-color:black;
      }
      [type=submit]{
          width:80%;
      }
  </style>


{% endblock %}

post/templates/post/search.html
{% if profiles %}
  <ul class='row mt-3' id='search-list'>
    {% for profile in profiles %}
    <a class='col-12 p-2 pl-3' href='{% url "profile" profile.username %}'>
    <li style="width: fit-content;">
      <div style="display: flex;"><img class='rounded-circle owner-username' id='search-pic'src='{{ profile.user.photo.url}} '>
        <ul style="list-style-type: none; padding-left:2%; height:fit-content;">
        <li style="font-weight: 600; margin-bottom: -45%; width:300%;">
          {{profile.username}}
        </li>
        <br>
        <li style="color:grey; font-weight: 400;width:300%;">
          {{profile.first_name}}
        </li>
      </ul>
    </li>
    </a>
    {% endfor %}
  </ul>
{% else %}
  <div id='no-result'>No results found.</div>
{% endif %}

post/templates/post/share_profile_search.html
{% if profiles %}
  <ul id='search-list'>

    {% for profile in profiles %}
    <li class='share-post' id='share-post-{{profile.id}}'>
      <div class="media p-0">
          <div class="media-left">
            <img class='rounded-circle' id='search-pic'src='{{ profile.user.photo.url}}'>              
          </div>
          <div class="media-body">
            <p class="media-heading m-0">
              <b> {{profile.username}} </b>
            </p>
            <p class='text-muted '>{{profile.first_name}}</p>
      </div>
      <br>
    </li>
    {% endfor %}
    
  </ul>

{% endif %}

post/templates/post/single_post.html
{% load static %}
{% load humanize %}
{% load time_format %}

<div class='col-8 d-none d-md-block' style="padding:0;">
  <img class="article-img" src="{{ post.photo.url }}" style="width: 100%; height: 85vh; border-right: rgb(230, 230, 230) solid 0.1px;"">    
</div>

<div class='col-12 col-md-4' style="padding:0;">

  <div class='post-metadata' style="padding:5% 2%; border-bottom: rgb(230, 230, 230) solid 0.1px;">
    <img class="rounded-circle article-img" src="{{ post.owner.user.photo.url }}" style="width:32px; height:32px; border-right: rgb(230, 230, 230) solid 0.1px;">
    <a class="mr-2" href="{% url 'profile' post.owner.username %}"><span class='owner-username'>{{post.owner.username}}</span></a>
  </div>


  <div class='comment-section comment-section-{{post.id}}' id='comment-section-{{post.id}}' style="overflow-y:scroll; scrollbar-width:none; overflow-x: hidden; height:45vh; border-bottom: rgb(230, 230, 230) solid 0.1px; margin:2% 1.5% !important;">
    {% for comment in post.post_comments.all %}
      <div class='media'>
        <div class="media-left">
          <img class='rounded-circle' src='{{comment.owner.user.photo.url}}'style="width:25px; height:25px;">
        </div>
        <div class="media-body">
          <span class='owner-username'><a href="{% url 'profile' comment.owner.username %}">{{comment.owner.username}}</a></span> {{comment.text}} <br>
          <small class="text-muted">{{ comment.created_at|timesince|shortUpto:',' }}</small>
          <small class="reply-btn text-muted pl-2" id='reply-btn-{{comment.id}}' style="cursor:pointer;">Reply</small>

          <div class='reply-section' id='reply-section-{{comment.id}}'>
          {% for reply in comment.comment_replies.all %}
            <div class='media'>
              <div class="media-left">
                <img class='rounded-circle' src='{{reply.owner.user.photo.url}}'style="width:25px; height:25px;">
              </div>
              <div class="media-body">
                <span class='owner-username'><a href="{% url 'profile' reply.owner.username %}">{{reply.owner.username}}</a> </span> {{reply.text}} <br>
                <small class="text-muted">{{ reply.created_at|timesince|shortUpto:',' }}</small>
              </div>
            </div>
            {% endfor %}
          </div>

        </div>
      </div>
    {% endfor %}
  </div>
  
    
    <div class='buttons col-12 d-inline-flex'>
      <div class='like_btn col-1'>
        <!-- like btn -->              
        <a onclick=
        "likePost('{% url 'post_unlike' post.id %}', {{ post.id }} );return false;"
        {% if post.id not in liked_posts %} style="display: none;" {% endif %}
        class="like-btn like-btn-{{post.id}}" id="like-btn-{{post.id}}">
          <svg aria-label="Unlike" class="_8-yf5 " fill="#ed4956" height="25" viewBox="0 0 48 48" width="26" >
            <path d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
            </path>
          </svg>
        </a>

        <!-- unlike btn -->
        <a onclick=
        "likePost('{% url 'post_like' post.id %}', {{ post.id }} );return false;"
        {% if post.id in liked_posts %} style="display: none;" {% endif %}
        class="unlike-btn unlike-btn-{{post.id}}" id="unlike-btn-{{post.id}}">
          <svg aria-label="Like" class="_8-yf5 " fill="#262626" height="25" viewBox="0 0 48 48" width="26" >
            <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
            </path>
          </svg>
        </a>
      </div>          

      <!-- comment btn -->
      <span class='col-1' id='comment_btn' style="cursor: pointer;">
        <svg aria-label="Comment" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24">
          <path clip-rule="evenodd" d="M47.5 46.1l-2.8-11c1.8-3.3 2.8-7.1 2.8-11.1C47.5 11 37 .5 24 .5S.5 11 .5 24 11 47.5 24 47.5c4 0 7.8-1 11.1-2.8l11 2.8c.8.2 1.6-.6 1.4-1.4zm-3-22.1c0 4-1 7-2.6 10-.2.4-.3.9-.2 1.4l2.1 8.4-8.3-2.1c-.5-.1-1-.1-1.4.2-1.8 1-5.2 2.6-10 2.6-11.4 0-20.6-9.2-20.6-20.5S12.7 3.5 24 3.5 44.5 12.7 44.5 24z" fill-rule="evenodd">
          </path>
        </svg>
      </span>

      <!-- share btn -->
      <span class='share_btn col-1'>
        <svg aria-label="Share Post" data-toggle="modal" data-target="#share-modal-{{post.id}}" fill="#262626" height="24" viewBox="0 0 48 48" width="24">
          <path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">
          </path>
        </svg>
      </span>        
      
      <!-- unsave btn -->     
      <div class='col-8 d-flex justify-content-end'>
      <div class='save_btn">'>
        <a onclick=
          "savePost('{% url 'post_unsave' post.id %}', {{ post.id }} );return false;"
          {% if post.id not in saved_posts %} style="display: none;" {% endif %}
          class="save-btn save-btn-{{post.id}}" id="save-btn-{{post.id}}">
            <!-- save btn -->
            <svg aria-label="Save" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24">
              <path d="M43.5 48c-.4 0-.8-.2-1.1-.4L24 28.9 5.6 47.6c-.4.4-1.1.6-1.6.3-.6-.2-1-.8-1-1.4v-45C3 .7 3.7 0 4.5 0h39c.8 0 1.5.7 1.5 1.5v45c0 .6-.4 1.2-.9 1.4-.2.1-.4.1-.6.1z">
              </path>
            </svg>  
          </a>
            
          <!-- save btn -->
          <a onclick=
          "savePost('{% url 'post_save' post.id %}', {{ post.id }} );return false;"
          {% if post.id in saved_posts %} style="display: none;" {% endif %}
          class="unsave-btn unsave-btn-{{post.id}}" id="unsave-btn-{{post.id}}">
          <!-- unsave btn -->
            <svg aria-label="Unsave" class="_8-yf5 " fill="#262626" height="24" viewBox="0 0 48 48" width="24" id='save_btn'>
              <path d="M43.5 48c-.4 0-.8-.2-1.1-.4L24 29 5.6 47.6c-.4.4-1.1.6-1.6.3-.6-.2-1-.8-1-1.4v-45C3 .7 3.7 0 4.5 0h39c.8 0 1.5.7 1.5 1.5v45c0 .6-.4 1.2-.9 1.4-.2.1-.4.1-.6.1zM24 26c.8 0 1.6.3 2.2.9l15.8 16V3H6v39.9l15.8-16c.6-.6 1.4-.9 2.2-.9z">
              </path>
            </svg>
          </a>
      </div>
      </div>
    </div>

    <div class="row">
      <div class='post-like post-like-{{post.id}} col-12' id='post-like-{{post.id}}'>
        {% if post.post_likes.count > 1 %}
        <span>{{post.post_likes.count}} likes</span>
        {% elif post.post_likes.count == 1 %}
        <span>{{post.post_likes.count}} like</span>
        {% else %}
        <small style="font-weight: lighter !important;"> Be the first one to <b>like this</b> </small>
        {% endif %}
      </div>
    </div>

    
    <!-- csrf token handled by javascript using global cookie -->
    <small class="text-muted d-none d-md-block position-absolute "style='bottom:10%;'>{{ post.created_at|timesince|upto:',' }}</small>
    <div class='modal-footer col-12 justify-content-start position-absolute' style="padding:4% 0 !important; bottom:0;">
      <form method="post" class='commentForm col-12 row' id='commentForm-{{post.id}}' name='commentForm' autocomplete="off">
        <span class='col-2'>
          <img class="rounded-circle post-owner-img" src="{{ user.user.photo.url }}" style="width:32px; height:32px;">
          <svg aria-label="Emoji" disabled fill="#262626" height="24" viewBox="0 0 48 48" width="24"><path d="M24 48C10.8 48 0 37.2 0 24S10.8 0 24 0s24 10.8 24 24-10.8 24-24 24zm0-45C12.4 3 3 12.4 3 24s9.4 21 21 21 21-9.4 21-21S35.6 3 24 3z"></path><path d="M34.9 24c0-1.4-1.1-2.5-2.5-2.5s-2.5 1.1-2.5 2.5 1.1 2.5 2.5 2.5 2.5-1.1 2.5-2.5zm-21.8 0c0-1.4 1.1-2.5 2.5-2.5s2.5 1.1 2.5 2.5-1.1 2.5-2.5 2.5-2.5-1.1-2.5-2.5zM24 37.3c-5.2 0-8-3.5-8.2-3.7-.5-.6-.4-1.6.2-2.1.6-.5 1.6-.4 2.1.2.1.1 2.1 2.5 5.8 2.5 3.7 0 5.8-2.5 5.8-2.5.5-.6 1.5-.7 2.1-.2.6.5.7 1.5.2 2.1 0 .2-2.8 3.7-8 3.7z"></path>
          </svg>
        </span>
        <span class='col-7 p-0' style="overflow: hidden; font-size: 80%;"> {{comment_form.text}} </span>
        <input type='submit' class='comment-submit ml-3 col-2' value="Post" style='background-color:white; padding:0;'> 
        <input type='hidden' name='url' id='url' value='{% url "post_comment_create" post.id %}'>
      </form>       
    </div> 
    
</div>

<script>
  var btn = document.querySelector('#comment_btn');
  var input = document.querySelector('#id_text'); // or getElementById

  btn.addEventListener('click', () => {
    input.focus();
  });
</script>